[package]
name = "imu"
version = "0.1.0"
edition = "2024"

[workspace]
resolver = "2"
members = ["compiler/*", "example/*", "runtime/*"]

[dependencies]
imuc_lexer = { path = "compiler/imuc_lexer", optional = true }
imuc_error = { path = "compiler/imuc_error", optional = true }
imuc_ast = { path = "compiler/imuc_ast", optional = true }
imuc_ctx = { path = "compiler/imuc_ctx", optional = true }
imuc_gen = { path = "compiler/imuc_gen", optional = true }
imuc_ir = { path = "compiler/imuc_ir", optional = true }
imuc_parser = { path = "compiler/imuc_parser", optional = true }
imuc_path = { path = "compiler/imuc_path", optional = true }
imuc_rules = { path = "compiler/imuc_rules", optional = true }
imuc_derive = { path = "compiler/imuc_derive", optional = true }
imuc_comp = { path = "compiler/imuc_comp", optional = true }
imur_mem = { path = "runtime/imur_mem", optional = true }
imur_io = { path = "runtime/imur_io", optional = true }
imur_error = { path = "runtime/imur_error", optional = true }
imur_proc = { path = "runtime/imur_proc", optional = true }

[features]
compiler = [
    "imuc_lexer",
    "imuc_error",
    "imuc_ast",
    "imuc_ctx",
    "imuc_gen",
    "imuc_ir",
    "imuc_parser",
    "imuc_path",
    "imuc_rules",
    "imuc_derive",
    "imuc_comp",
]
runtime = ["imur_mem", "imur_io", "imur_error", "imur_proc"]
