[package]
name = "imu"
version = "0.1.0"
edition = "2021"

[workspace]
resolver = "2"
members = ["compiler/*"]

[dependencies]
imuc_lexer = { path = "compiler/imuc_lexer", optional = true }
imuc_error = { path = "compiler/imuc_error", optional = true }
