use super::Body;
use crate::prelude::*;
use cmd::{Bytes, Cmd, Ptr};
use std::collections::{BTreeMap, HashMap};
use std::ops::Deref;
use std::sync::{Arc, RwLock};
use sym::{
    ty::{TyInner, TyKind},
    Fun, FunSig, Ty,
};

type GlobMap = HashMap<StrRef, Glob>;

/// A shared lock to the globals
pub type GlobsHandle = Arc<RwLock<Globs>>;

/// A global variable that can be accessed or created in the current module
///
/// If `Self::kind`] is [`GlobKind::External`, this will not be exported,
/// otherwise the corresponding global will be written to the output file
///
/// `Self::ty` is the bare type of the global. However most of the time a ptr wrapping this ty is required
///
/// You can omit the type checking when acquiring a global, because the name implies the type
pub struct Glob {
    ptr: Ptr,
    ty: Ty,
    kind: GlobKind,
}

impl Glob {
    pub fn new(ptr: Ptr, ty: Ty, kind: GlobKind) -> Self {
        Self { ptr, ty, kind }
    }

    /// Returns the global's pointer
    pub fn ptr(&self) -> Ptr {
        self.ptr
    }

    /// Returns the global's type reference
    pub fn ty(&self) -> &Ty {
        &self.ty
    }

    /// Returns whether the global is external and has no details
    pub fn external(&self) -> bool {
        matches!(self.kind, GlobKind::External)
    }

    /// Returns the global's kind
    pub fn kind(&self) -> &GlobKind {
        &self.kind
    }
}

/// Stores the type and detailed data of the `Glob` variable, such as function internals;
/// Or, as an external type, the details are omitted and only referenced by ptr
#[derive(Default)]
pub enum GlobKind {
    #[default]
    External,
    Fun(Fun),
}

/// A map used in `Ctx`(`super::Ctx`) for compiling global variables with a static, mangled name
///
/// This also stores a ptr to the top of globals stack
#[derive(Default)]
pub struct Globs {
    map: GlobMap,
    stack: Ptr,
}

impl Deref for Globs {
    type Target = GlobMap;
    fn deref(&self) -> &Self::Target {
        &self.map
    }
}

/// The exported results of all globals that are external
/// This is only generated by `Globs`
#[derive(Default)]
pub struct ExportGlobs {
    pub fun: BTreeMap<StrRef, Fun>,
}

impl Globs {
    /// Inserts a ptr to a global with a key into the global map
    ///
    /// TODO: This is not made global, because general global exporting is not supported at present
    fn insert(&mut self, name: StrRef, glob: Glob) {
        self.map.insert(name, glob);
    }

    /// Loads a function with given name as an *external*, pushing commands and references into the body
    ///
    /// You must input the *bottom*(base) body into this function to prevent multiple calls
    pub fn load_fun(&mut self, body: &mut Body, name: StrRef, ty: Ty) {
        self.load_fun_with(body, name, ty, Cmd::Link);
    }

    /// Loads the function with the `Cmd::LinkCheck`] commands, see [`Self::load_fun` for details
    pub fn load_fun_check(
        &mut self,
        body: &mut Body,
        name: StrRef,
        ty: Ty,
        param: Bytes,
        ret: Bytes,
    ) {
        self.load_fun_with(body, name, ty, move |name| Cmd::LinkCheck(param, ret, name));
    }

    /// Helper function for both `Self::load_fun`] and [`Self::load_fun_check`. See load_fun for
    /// details
    fn load_fun_with(
        &mut self,
        body: &mut Body,
        name: StrRef,
        ty: Ty,
        gen_cmd: impl FnOnce(StrRef) -> Cmd,
    ) {
        let ptr = self.stack;
        body.push_void(gen_cmd(name.clone()));
        self.stack += Bytes::ptr();
        self.insert(name, Glob::new(ptr, ty, GlobKind::External));
    }

    /// Merges an iterator of *external* functions into globals, assigning each with a ptr, if not already
    ///
    /// You must input the *bottom*(base) body into this function to prevent multiple calls
    ///
    /// Normally, the argument of this function is read from header files
    pub fn merge_fun<'a, I>(&mut self, body: &mut Body, funs: I)
    where
        I: IntoIterator<Item = (&'a StrRef, &'a FunSig)>,
    {
        for (name, sig) in funs.into_iter() {
            // Only unassigned names are used
            if !self.contains_key(name) {
                let ty = Ty::new(TyInner::new(
                    name.clone(),
                    TyKind::Fun {
                        param: sig.param.clone(),
                        ret: sig.ret.clone(),
                    },
                ));
                let ptr_ty = Ty::new(TyInner::new(
                    super::mangle::mangle_ptr(ty.name.as_str()).into(),
                    TyKind::Ptr(sym::ty::TyItem::Solid(ty)),
                ));
                self.load_fun(body, name.clone(), ptr_ty);
            }
        }
    }

    /// Takes all non-external globals of the map, and returns them in `ExportGlobs`,
    /// note that this will turn all non-external globals into external globals
    pub fn export_globs(&mut self) -> ExportGlobs {
        let mut export = ExportGlobs::default();
        for (name, glob) in self.map.iter_mut() {
            match std::mem::take(&mut glob.kind) {
                GlobKind::External => {}
                GlobKind::Fun(fun) => {
                    export.fun.insert(name.to_owned(), fun);
                }
            }
        }
        export
    }
}
