[package]
name = "imuc_gen"
version = "0.1.0"
edition = "2021"

[dependencies]
imuc_ast = { path = "../imuc_ast" }
imuc_error = { path = "../imuc_error" }
imuc_ir = { path = "../imuc_ir" }
imuc_ctx = { path = "../imuc_ctx" }
